### ISSUE TITLE
Cookie大概是什么格式啊？我复制了一些东西进去但都出错

### ISSUE THREAD

**Issue by vivianc2** [idootop/mi-note-export#1]
大概这样？
kCookie='i.mi.com_istrudev=true; i.mi.com_isvalid_servicetoken=true; i.mi.com_ph=xxxxxxxxxxx==; i.mi.com_slh=xxxxxxxxxxx=; iplocale=en_US; serviceToken=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx==; uLocale=en_US; userId=xxxxxxxxxx'

我是从inspect的network里面找的，但是很多都不一样？
报错是：

error An unexpected error occurred: "https://registry.npmmirror.com/object.assign/-/object.assign-4.1.4.tgz: incorrect data check".

谢谢！

**Comment by idootop** [comment]
你找的 cookie 格式没问题，上面的报错是你在拉取 npm 依赖的时候，数据格式校验异常。

显然跟你使用的 npmmirror.com 代理有关，可以尝试更换到其他 npm 镜像站 or 使用 npm 官方源。

自行解决。
